### ISSUE TITLE
Set-up/dependency issues (Python 3.7.1, Python 3.6.6, Python 3.4.9)

### ISSUE THREAD

**Issue by ADubhlaoich** [django-danceschool/django-danceschool#100]
Messing around with a few permutations of installs.

**Python 3.7.1**
`pip install django-danceschool`
```
django-filer 1.3.2 has requirement Unidecode<0.05,>=0.04, but you'll have unidecode 1.0.22 which is incompatible.
xhtml2pdf 0.2.3 has requirement html5lib>=1.0, but you'll have html5lib 0.9999999 which is incompatible.
```
It weathers through into installing anyway - I haven't tried mangling together an attempt to fix yet but might be solvable just messing around with the pipfile library versions..

`python manage.py migrate`
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
    from django.contrib.admin.filters import (
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 10, in <module>
    from django.contrib.admin.options import IncorrectLookupParameters
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/contrib/admin/options.py", line 13, in <module>
    from django.contrib.admin import helpers, widgets
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
```
This specifically looks like a [python 3.7](https://bugs.python.org/issue32012) issue related to [Django 1.11.x](https://code.djangoproject.com/ticket/28814) that could be fixed with a bump up to Django 2.0 or above.

**Python 3.6.6**
`pip install django-danceschool`

`djangocms-text-ckeditor 3.6.0 has requirement html5lib!=0.9999,!=0.99999,<0.99999999,>=0.90, but you'll have html5lib 1.0.1 which is incompatible.`

Similar issue as for above with 3.7.1.

`python manage.py migrate`
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/danceschool/core/models.py", line 14, in <module>
    from djangocms_text_ckeditor.fields import HTMLField
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/djangocms_text_ckeditor/fields.py", line 7, in <module>
    from .html import clean_html
  File "/home/adubhlaoich/.local/share/virtualenvs/Misfit-WDMrUYm2/lib/python3.6/site-packages/djangocms_text_ckeditor/html.py", line 9, in <module>
    from html5lib import sanitizer, serializer, treebuilders, treewalkers
ImportError: cannot import name 'sanitizer'
```
Finally...

**Python 3.4.9**
`pip install django-danceschool`
`xhtml2pdf 0.2.3 has requirement html5lib>=1.0, but you'll have html5lib 0.9999999 which is incompatible.`

Migrations and everything else sets up fine from here - I hadn't tried a Python 3.5 install.

**Comment by leetucker** [comment]
Re: the Python 3.7 issue, Django CMS 3.5.2 does not support Django 2.0 or Django 2.1.  A commit to the repository has added this support, so it should come with the next release, but in the meantime that probably means we can't support Python 3.7.  I've updated the README and installation docs to reflect this.

Re: the other issues, I think that this html5lib version bug is something that I've dealt with.  The requirements files for the production-template and development-template repos don't have this problem I believe, and this is because of something in the requirements.txt files for each of those repos, but I don't recall what the trick was.  I can look into this and then modify requirements.txt in the main repository to incorporate the necessary fix.
