### ISSUE TITLE
setupschool fails - can't import InstructorListPluginModel

### ISSUE THREAD

**Issue by kirkalicious** [django-danceschool/django-danceschool#108]
After running through the basic setup instructions, the `python manage.py setupschool` command failed with the following error:
```
python manage.py setupschool
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kirk.tarou/.pyenv/versions/danceschool/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/kirk.tarou/.pyenv/versions/danceschool/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kirk.tarou/.pyenv/versions/danceschool/lib/python3.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/kirk.tarou/.pyenv/versions/danceschool/lib/python3.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/kirk.tarou/.pyenv/versions/3.7.1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kirk.tarou/.pyenv/versions/danceschool/lib/python3.7/site-packages/danceschool/core/management/commands/setupschool.py", line 9, in <module>
    from danceschool.core.models import DanceType, DanceTypeLevel, DanceRole, PricingTier, InstructorListPluginModel
ImportError: cannot import name 'InstructorListPluginModel' from 'danceschool.core.models' (/Users/kirk.tarou/.pyenv/versions/danceschool/lib/python3.7/site-packages/danceschool/core/models.py)
```

I'm running with python 3.7.1 on OSX.

**Comment by benjwrdill** [comment]
This looks like it is related to changes made in #460fcc3b42ba46cfa743a29479bf3f35603f7877. I've got a partial fix working locally by searching and replacing `InstructorListPluginModel` with `StaffMemberListPluginModel`, but the `setupschool` command is still failing when creating the initial list of instructors.

**Comment by merwok** [comment]
The command is failing how?
