### ISSUE TITLE
Error providing refund using Square API

### ISSUE THREAD

**Issue by riclima** [django-danceschool/django-danceschool#112]
Getting a internal server error with this message on the log when attempting a refund using Square's API:

```

Dec 20 06:45:03 somehost gunicorn[3886]: Error in providing Square refund.
Dec 20 06:45:05 somehost gunicorn[3886]: [2018-12-20 06:45:05 -0500] [3894] [ERROR] Error handling request /invoice/refund/confirm/?confirmed=True
Dec 20 06:45:05 somehost gunicorn[3886]: Traceback (most recent call last):
Dec 20 06:45:05 somehost gunicorn[3886]:   File "/home/somedanceschoolapp/.virtualenvs/somedanceschoolapp/lib/python3.5/site-packages/danceschool/payments/square/models.py", line 114, in refund
Dec 20 06:45:05 somehost gunicorn[3886]:     location_id=self.locationId,transaction_id=self.transactionId,body=body
Dec 20 06:45:05 somehost gunicorn[3886]:   File "/home/somedanceschoolapp/.virtualenvs/somedanceschoolapp/lib/python3.5/site-packages/squareconnect/apis/transactions_api.py", line 299, in create_refund
Dec 20 06:45:05 somehost gunicorn[3886]:     callback=params.get('callback'))
Dec 20 06:45:05 somehost gunicorn[3886]:   File "/home/somedanceschoolapp/.virtualenvs/somedanceschoolapp/lib/python3.5/site-packages/squareconnect/api_client.py", line 316, in call_api
Dec 20 06:45:05 somehost gunicorn[3886]:     response_type, auth_settings, callback)
Dec 20 06:45:05 somehost gunicorn[3886]:   File "/home/somedanceschoolapp/.virtualenvs/somedanceschoolapp/lib/python3.5/site-packages/squareconnect/api_client.py", line 143, in __call_api
Dec 20 06:45:05 somehost gunicorn[3886]:     post_params=post_params, body=body)
Dec 20 06:45:05 somehost gunicorn[3886]:   File "/home/somedanceschoolapp/.virtualenvs/somedanceschoolapp/lib/python3.5/site-packages/squareconnect/api_client.py", line 352, in request
Dec 20 06:45:05 somehost gunicorn[3886]:     body=body)
Dec 20 06:45:05 somehost gunicorn[3886]:   File "/home/somedanceschoolapp/.virtualenvs/somedanceschoolapp/lib/python3.5/site-packages/squareconnect/rest.py", line 237, in POST
Dec 20 06:45:05 somehost gunicorn[3886]:     body=body)
Dec 20 06:45:05 somehost gunicorn[3886]:   File "/home/somedanceschoolapp/.virtualenvs/somedanceschoolapp/lib/python3.5/site-packages/squareconnect/rest.py", line 205, in request
Dec 20 06:45:05 somehost gunicorn[3886]:     raise ApiException(http_resp=r)
Dec 20 06:45:05 somehost gunicorn[3886]: squareconnect.rest.ApiException: (401)
Dec 20 06:45:05 somehost gunicorn[3886]: Reason: Unauthorized
Dec 20 06:45:05 somehost gunicorn[3886]: HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 20 Dec 2018 11:45:03 GMT', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=631152000', 'X-Download-Options': 'noopen', 'X-Xss-Protection': '1; mode=block', 'Content-Type': 'application/json', 'keep-alive': 'timeout=60', 'X-Frame-Options': 'SAMEORIGIN', 'content-length': '569', 'X-Permitted-Cross-Domain-Policies': 'none', 'Vary': 'Origin, Accept-Encoding'})
Dec 20 06:45:05 somehost gunicorn[3886]: HTTP response body: {"errors":[{"category":"AUTHENTICATION_ERROR","code":"UNAUTHORIZED","detail":"The `Authorization` http header of your request was malformed. The header value is expected to be of the format \"Bearer TOKEN\" (without quotation marks), where TOKEN is to be replaced with your access token (e.g. \"Bearer ABC123def456GHI789jkl0\"). For more information, see https://docs.connect.squareup.com/api/connect/v2/#requestandresponseheaders. If you are seeing this error message while using one of our officially supported SDKs, please report this to developers@squareup.com."}]}
```

**Comment by leetucker** [comment]
This should be fixed as of version 0.8.1.  There was a change a few months ago in which the Square API changed, and although I corrected for the API change in the standard online payment mechanisms, I forgot to make the same change in the refund mechanisms.  I'm closing this, but let me know if you run into any additional issues.
