### ISSUE TITLE
Initial migrate is failing

### ISSUE THREAD

**Issue by Tahvok** [django-danceschool/django-danceschool#149]
Hello

I'm using the docker build from production-template repository.

During the first run of migrate, this is what I got:

```
Initializing database migrations. This may take a minute.
Operations to perform:
  Apply all migrations: account, admin, auth, banlist, bootstrap4_alerts, bootstrap4_badge, bootstrap4_card, bootstrap4_carousel, bootstrap4_collapse, bootstrap4_content, bootstrap4_grid, bootstrap4_jumbotron, bootstrap4_link, bootstrap4_listgroup, bootstrap4_media, bootstrap4_picture, bootstrap4_tabs, bootstrap4_utilities, cms, contenttypes, core, discounts, djangocms_forms, djangocms_icon, djangocms_link, djangocms_picture, djangocms_text_ckeditor, dynamic_preferences, easy_thumbnails, faq, filer, financial, guestlist, menus, news, prerequisites, private_events, sessions, sites, socialaccount, stats, vouchers
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying filer.0001_initial... OK
  Applying filer.0002_auto_20150606_2003... OK
  Applying filer.0003_thumbnailoption... OK
  Applying filer.0004_auto_20160328_1434... OK
  Applying filer.0005_auto_20160623_1425... OK
  Applying filer.0006_auto_20160623_1627... OK
  Applying filer.0007_auto_20161016_1055... OK
  Applying banlist.0001_initial... OK
  Applying banlist.0002_auto_20181114_2144... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207... OK
  Applying cms.0013_urlconfrevision... OK
  Applying cms.0014_auto_20160404_1908... OK
  Applying cms.0015_auto_20160421_0000... OK
  Applying cms.0016_auto_20160608_1535... OK
  Applying bootstrap4_alerts.0001_initial... OK
  Applying bootstrap4_badge.0001_initial... OK
  Applying bootstrap4_card.0001_initial... OK
  Applying filer.0008_auto_20171117_1313... OK
  Applying filer.0009_auto_20171220_1635... OK
  Applying filer.0010_auto_20180414_2058... OK
  Applying filer.0011_auto_20190418_0137... OK
  Applying bootstrap4_carousel.0001_initial... OK
  Applying bootstrap4_carousel.0002_bootstrap4carousel_carousel_aspect_ratio... OK
  Applying bootstrap4_carousel.0003_auto_20180610_1102... OK
  Applying bootstrap4_carousel.0004_auto_20190703_0831... OK
  Applying bootstrap4_collapse.0001_initial... OK
  Applying bootstrap4_content.0001_initial... OK
  Applying bootstrap4_content.0002_added_figure... OK
  Applying bootstrap4_grid.0001_initial... OK
  Applying bootstrap4_grid.0002_auto_20180709_0808... OK
  Applying bootstrap4_grid.0003_migrate_column_size... OK
  Applying bootstrap4_grid.0004_remove_bootstrap4gridcolumn_column_size... OK
  Applying bootstrap4_jumbotron.0001_initial... OK
  Applying bootstrap4_link.0001_initial... OK
  Applying bootstrap4_link.0002_add_icons... OK
  Applying bootstrap4_link.0003_icon_updates... OK
  Applying bootstrap4_link.0004_auto_20190703_0831... OK
  Applying bootstrap4_listgroup.0001_initial... OK
  Applying bootstrap4_media.0001_initial... OK
  Applying djangocms_picture.0001_initial... OK
  Applying djangocms_picture.0002_auto_20151018_1927... OK
  Applying djangocms_picture.0003_migrate_to_filer... OK
  Applying djangocms_picture.0004_adapt_fields... OK
  Applying djangocms_picture.0005_reset_null_values... OK
  Applying djangocms_picture.0006_remove_null_values... OK
  Applying djangocms_picture.0007_fix_alignment... OK
  Applying djangocms_picture.0008_picture_use_responsive_image... OK
  Applying bootstrap4_picture.0001_initial... OK
  Applying bootstrap4_picture.0002_bootstrap4picture_use_responsive_image... OK
  Applying bootstrap4_picture.0003_auto_20181212_1055... OK
  Applying bootstrap4_picture.0004_auto_20190703_0831... OK
  Applying bootstrap4_tabs.0001_initial... OK
  Applying bootstrap4_tabs.0002_auto_20180610_1106... OK
  Applying bootstrap4_utilities.0001_initial... OK
  Applying cms.0017_pagetype... OK
  Applying cms.0018_create_pagenode... OK
  Applying cms.0019_set_pagenode...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python3.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python3.7/site-packages/cms/migrations/0019_set_pagenode.py", line 68, in apply
    connection.introspection.get_table_description(connection.cursor(), 'cms_page')
  File "/usr/lib/python3.7/site-packages/django/db/backends/postgresql/introspection.py", line 87, in get_table_description
    )) for line in cursor.description
  File "/usr/lib/python3.7/site-packages/django/db/backends/postgresql/introspection.py", line 87, in <listcomp>
    )) for line in cursor.description
TypeError: sequence index must be integer, not 'slice'
```

And when I try to rerun it I'm getting this:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python3.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python3.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/lib/python3.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/web/school/urls.py", line 32, in <module>
    url(r'^', include('cms.urls')),
  File "/usr/lib/python3.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/cms/urls.py", line 19, in <module>
    urlpatterns = get_app_patterns()
  File "/usr/lib/python3.7/site-packages/cms/appresolver.py", line 202, in get_app_patterns
    site = get_current_site()
  File "/usr/lib/python3.7/site-packages/cms/utils/__init__.py", line 16, in get_current_site
    return Site.objects.get_current()
  File "/usr/lib/python3.7/site-packages/django/contrib/sites/models.py", line 63, in get_current
    return self._get_site_by_id(site_id)
  File "/usr/lib/python3.7/site-packages/django/contrib/sites/models.py", line 35, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/usr/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.sites.models.DoesNotExist: Site matching query does not exist.
```

Now I don't know how (and if) I should proceed

**Comment by Tahvok** [comment]
Looks like this issue is similar:
https://github.com/divio/django-cms/issues/6666

I've put the following in requirements.txt:
psycopg2>=2.7,<2.8

And it's passing this step. However, it's now failing at the following step:
```
Applying vouchers.0005_publiceventcategoryvoucher_seriescategoryvoucher_sessionvoucher... OK
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField ExpenseItem.submissionDate received a naive datetime (2019-11-12 14:51:04.140998) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField ExpenseItem.submissionDate received a naive datetime (2019-11-12 14:51:04.158879) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField RevenueItem.submissionDate received a naive datetime (2019-11-12 14:51:05.013701) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField RevenueItem.submissionDate received a naive datetime (2019-11-12 14:51:05.013804) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField ExpenseItem.submissionDate received a naive datetime (2019-11-12 14:51:05.160420) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField RevenueItem.submissionDate received a naive datetime (2019-11-12 14:51:05.199692) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField NewsItem.publicationDate received a naive datetime (2019-11-12 14:51:12.842866) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField NewsItem.publicationDate received a naive datetime (2019-11-12 14:51:12.842961) while time zone support is active.
  RuntimeWarning)
/usr/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField NewsItem.publicationDate received a naive datetime (2019-11-12 14:51:12.877164) while time zone support is active.
  RuntimeWarning)
```

**Comment by afs2015** [comment]
Thanks for bringing this to our attention. @leetucker do you have any insight on this?
