### ISSUE TITLE
StaffDirectoryView causing no instructors to show on Instructor Page

### ISSUE THREAD

**Issue by afs2015** [django-danceschool/django-danceschool#152]
Currently on our instructor page https://bostonlindyhop.com/instructors/ no instructors are showing up. I have noticed https://newcolumbiaswing.org/about/instructors/ has the same issue as well.

I believe the issue is in the file `danceschool/core/views.py` that the line `staff = context.get('staffmember_list', StaffMember.objects.none())` in `StaffDirectoryView` is returning None instead of `staffmember_list`.

**Comment by leetucker** [comment]
It looks like the issue was actually in `StaffMemberListPlugin` in `core/cms_plugins.py`.  Apparently the multi-select field for instructor status no longer resolves to a list by default, which was causing the staff member query to always come up empty.  I fixed the issue by forcing statusChoices to resolve as a list.

**Comment by JonBendtsen** [comment]
I think I'm hit by this issue as well

```
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:55:21 +0000] "GET /instructors/ HTTP/2.0" 500 145 "https://registration.balboaswing.dk/classes/2023/September/r5-2023-beginners/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 13.5; rv:91.0) Gecko/20100101 Firefox/91.0 SeaMonkey/2.53.16"
```

same issue in Brave Browser and Safari.

I also get errors like these

```
nginx.1     | 2023/08/08 18:48:55 [error] 81#81: *962 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /admin/jsi18n/ HTTP/2.0", upstream: "http://10.0.2.8:8000/admin/jsi18n/", host: "registration.balboaswing.dk", referrer: "https://registration.balboaswing.dk/admin/core/staffmember/"
nginx.1     | 2023/08/08 18:48:55 [warn] 81#81: *962 upstream server temporarily disabled while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /admin/jsi18n/ HTTP/2.0", upstream: "http://10.0.2.8:8000/admin/jsi18n/", host: "registration.balboaswing.dk", referrer: "https://registration.balboaswing.dk/admin/core/staffmember/"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:48:55 +0000] "GET /admin/jsi18n/ HTTP/2.0" 200 3187 "https://registration.balboaswing.dk/admin/core/staffmember/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:48:55 +0000] "GET /admin/core/staffmember/ HTTP/2.0" 200 33678 "https://registration.balboaswing.dk/admin/core/staffmember/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:48:55 +0000] "GET /admin/jsi18n/ HTTP/2.0" 200 3187 "https://registration.balboaswing.dk/admin/core/staffmember/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:51:04 +0000] "HEAD / HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:51:17 +0000] "GET / HTTP/1.1" 200 4330 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
nginx.1     | 2023/08/08 18:54:40 [error] 81#81: *1017 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /instructors/ HTTP/2.0", upstream: "http://10.0.2.8:8000/instructors/", host: "registration.balboaswing.dk", referrer: "https://registration.balboaswing.dk/classes/2023/September/r5-2023-beginners/"
nginx.1     | 2023/08/08 18:54:40 [warn] 81#81: *1017 upstream server temporarily disabled while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /instructors/ HTTP/2.0", upstream: "http://10.0.2.8:8000/instructors/", host: "registration.balboaswing.dk", referrer: "https://registration.balboaswing.dk/classes/2023/September/r5-2023-beginners/"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:54:40 +0000] "GET /instructors/ HTTP/2.0" 500 145 "https://registration.balboaswing.dk/classes/2023/September/r5-2023-beginners/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 13.5; rv:91.0) Gecko/20100101 Firefox/91.0 SeaMonkey/2.53.16"


nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:55:21 +0000] "GET /instructors/ HTTP/2.0" 500 145 "https://registration.balboaswing.dk/classes/2023/September/r5-2023-beginners/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 13.5; rv:91.0) Gecko/20100101 Firefox/91.0 SeaMonkey/2.53.16"
nginx.1     | 49.13.75.126 10.0.0.2 - - [08/Aug/2023:18:55:48 +0000] "POST /boaform/admin/formLogin HTTP/1.1" 503 197 "http://49.13.75.126:80/admin/login.asp" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
nginx.1     | _ 10.0.0.2 - - [08/Aug/2023:18:55:48 +0000] "" 400 0 "-" "-"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:55:59 +0000] "GET /instructors/ HTTP/2.0" 500 145 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
nginx.1     | 2023/08/08 18:55:59 [error] 81#81: *1022 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /favicon.ico HTTP/2.0", upstream: "http://10.0.2.8:8000/favicon.ico", host: "registration.balboaswing.dk", referrer: "https://registration.balboaswing.dk/instructors/"
nginx.1     | 2023/08/08 18:55:59 [warn] 81#81: *1022 upstream server temporarily disabled while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /favicon.ico HTTP/2.0", upstream: "http://10.0.2.8:8000/favicon.ico", host: "registration.balboaswing.dk", referrer: "https://registration.balboaswing.dk/instructors/"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:55:59 +0000] "GET /favicon.ico HTTP/2.0" 301 0 "https://registration.balboaswing.dk/instructors/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
nginx.1     | registration.balboaswing.dk 10.0.0.2 - - [08/Aug/2023:18:55:59 +0000] "GET /favicon.ico/ HTTP/2.0" 404 179 "https://registration.balboaswing.dk/instructors/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
nginx.1     | 2023/08/08 18:56:14 [error] 81#81: *1027 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /favicon.ico HTTP/2.0", upstream: "http://10.0.2.8:8000/favicon.ico", host: "registration.balboaswing.dk"
nginx.1     | 2023/08/08 18:56:14 [warn] 81#81: *1027 upstream server temporarily disabled while connecting to upstream, client: 10.0.0.2, server: registration.balboaswing.dk, request: "GET /favicon.ico HTTP/2.0", upstream: "http://10.0.2.8:8000/favicon.ico", host: "registration.balboaswing.dk"
```

**Comment by JonBendtsen** [comment]
```
Internal Server Error: /instructors/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/sekizai/templatetags/sekizai_tags.py", line 87, in render_tag
    rendered_contents = nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/sekizai/templatetags/sekizai_tags.py", line 87, in render_tag
    rendered_contents = nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/cms/templatetags/cms_tags.py", line 433, in render_tag
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/cms/templatetags/cms_tags.py", line 294, in render_tag
    content = renderer.render_page_placeholder(
  File "/usr/local/lib/python3.10/site-packages/cms/plugin_rendering.py", line 329, in render_page_placeholder
    content = self.render_placeholder(
  File "/usr/local/lib/python3.10/site-packages/cms/plugin_rendering.py", line 251, in render_placeholder
    placeholder_content = ''.join(plugin_content)
  File "/usr/local/lib/python3.10/site-packages/cms/plugin_rendering.py", line 447, in render_plugins
    yield self.render_plugin(plugin, context, placeholder, editable)
  File "/usr/local/lib/python3.10/site-packages/cms/plugin_rendering.py", line 424, in render_plugin
    template = self.templates.get_cached_template(template)
  File "/usr/local/lib/python3.10/site-packages/cms/templates.py", line 18, in get_cached_template
    self._cached_templates[template] = get_template(template)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: core/instructor_image_set.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: core/instructor_image_set.html

```

**Comment by JonBendtsen** [comment]
Maybe the issue is that I did not upload any pictures on my instructors, will test that.

**Comment by JonBendtsen** [comment]
nope, adding pictures did not change anything

**Comment by JonBendtsen** [comment]
probably file should be here

/usr/local/lib/python3.10/site-packages/danceschool/core/templates/core

where there are no file named instructor_image_set.html, but there is a staff_image_set.html, maybe I can just symlink that?

Contents mention instructor :-D

Nope, didn't work, same error.

inside the "web" container.

**Comment by JonBendtsen** [comment]
In production-template/docker/web/Dockerfile I added this line
`RUN cp -a /usr/local/lib/python3.10/site-packages/danceschool/core/templates/core/staff_image_set.html /usr/local/lib/python3.10/site-packages/danceschool/core/templates/core/instructor_image_set.html`

And now I do not get any error message, but I'm not seeing any Instructors either ?

**Comment by JonBendtsen** [comment]
Text not the most descriptive in the bottom of `/admin/core/staffmember/2/change/` under
```
Instructor information

[Add another Instructor](https://registration.balboaswing.dk/admin/core/staffmember/2/change/#)
```


I don't want to add another instructor, but if I click Add another instructor, then I get to select `Instructor information`

even after setting this to `Regular Instructor` I still can not see any instructors?

**Comment by afs2015** [comment]
@JonBendtsen: Did https://github.com/django-danceschool/django-danceschool/commit/d0b34dc4690c90280badcdee041f2ed4e1ddfbb0 fix your issue or are you still seeing it?

**Comment by JonBendtsen** [comment]
> @JonBendtsen: Did [d0b34dc](https://github.com/django-danceschool/django-danceschool/commit/d0b34dc4690c90280badcdee041f2ed4e1ddfbb0) fix your issue or are you still seeing it?

I stopped using Django-danceschool about a shortly after I posted the above. Instead I've build my own system that we already use for organizing events and classes.

After presenting it in Herrang this summer my plan is to launch a paid service because a service seemed like what most people wanted rather than a DIY, run it yourself.

I am able to launch it already now, but I would like to wait until Januar 1st because if I do it before I'd have to still do taxes from the period now until the end of the year, where as if I start the business January 1st I'd get a whole year before having to do taxes.

Given that I store peoples private information, and I live in the EU, I'd have to abide by the GDPR laws and due to all that hassle and risk I'd would not offer the service for free.

My system can do classes, event, customers, vendors, contacts on these, waiting lists, membership, payments using stripe, paypal or banktransfer. Even cash. It has user capabilities, like in our dance org. there's the boards which has almost all permisions (I have more), then the teachers which has less, and below that there's volunteers, ... 

So far I can accept lead or follow role, but solo, ELEF, AMBI or switch should be easy to add. People can register as a lone wolf, with a partner and as a couple. With a partner both has to register. As a couple only one person registers, pays for both and handles all communication. This is often used by married couples.

I do not currently have automatic accept, everyone gets on a waiting list, then from the overview page I can see the registrants, their status, and click through and accept them.

I'm got linking to work when both parties register with partner, each mentioning each other. But if only one does, then it can not yet recognize. So, manual accept, automatic will come. As with many more features.
