### ISSUE TITLE
Class Series editing fails if you delete an in-use ClassDescription

### ISSUE THREAD

**Issue by NorthIsUp** [django-danceschool/django-danceschool#68]
```
Save method for Event or subclass called.
About to check registration status and update if needed.
Beginning update registration status.  saveMethod=True
Returning value: False
Finished checking status and ready for super call. Value is False
Internal Server Error: /admin/core/event/
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1609, in changelist_view
    self.log_change(request, obj, change_msg)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 735, in log_change
    object_repr=force_text(object),
  File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/app/.heroku/src/danceschool/danceschool/core/models.py", line 1186, in __str__
    return month_name[self.month or 0] + ' ' + str(self.year) + ": " + self.classDescription.title
AttributeError: 'NoneType' object has no attribute 'title'
```

**Comment by leetucker** [comment]
All set.
