### ISSUE TITLE
Possible pip dependency/requirements issue

### ISSUE THREAD

**Issue by ADubhlaoich** [django-danceschool/django-danceschool#80]
Following the basic installation instructions in the README, I'm failing to set-up django-danceschool properly during step 5 of database migration. I've tested this with both a bare virtualenv set-up and [pipenv](https://docs.pipenv.org/), which both raise the same issue.

`python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/polymorphic/__init__.py", line 13, in <module>
    __version__ = pkg_resources.require("django-polymorphic")[0].version
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.10.8 (/home/adubhlaoich/Projects/misvir/lib/python3.6/site-packages), Requirement.parse('Django>=1.11'), {'django-polymorphic'})`

**Comment by kirkalicious** [comment]
Try editing the requirements.txt file and change django-polymorphic==1.3

The current release of django-polymorphic supports Django 1.11, 2.0 and Python 2.7 and 3.4+ is supported. For older Django versions, install django-polymorphic==1.3.

**Comment by ADubhlaoich** [comment]
Works as intended, thanks!

I've been talking to @afs2015 about updating the README as a temporary measure, and will submit a PR later this week.

**Comment by leetucker** [comment]
I'm going to fix this simultaneously with updating everything to use Django CMS 3.5 and Django 1.11.  I'll try to get to it sooner rather than later.

**Comment by leetucker** [comment]
Fixed with the new release!
